/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ffb77d",
        "primary-container": "#ff8c00",
        "primary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#ffb77d",
        "on-primary": "#4d2600",
        "on-primary-container": "#623200",
        "on-primary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#6e3900",
        "inverse-primary": "#904d00",
        "secondary": "#adc6ff",
        "secondary-container": "#4b8eff",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary": "#002e69",
        "on-secondary-container": "#00285c",
        "on-secondary-fixed": "#001a41",
        "on-secondary-fixed-variant": "#004493",
        "tertiary": "#85cfff",
        "tertiary-container": "#00b5fc",
        "tertiary-fixed": "#c7e7ff",
        "tertiary-fixed-dim": "#85cfff",
        "on-tertiary": "#00344c",
        "on-tertiary-container": "#004360",
        "on-tertiary-fixed": "#001e2e",
        "on-tertiary-fixed-variant": "#004c6c",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "background": "#131313",
        "on-background": "#e2e2e2",
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-tint": "#ffb77d",
        "surface-variant": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#ddc1ae",
        "outline": "#a48c7a",
        "outline-variant": "#564334",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
